// <auto-generated />
namespace Bookstore_ITProekt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class requiredKeys2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(requiredKeys2));
        
        string IMigrationMetadata.Id
        {
            get { return "201910022143090_requiredKeys2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
